site_name: MCPlayHelp
site_description: 'MCPlay Wiki'
site_author: 'GravittoGroup, MCPlay Team'
site_url: 'https://wiki.mcplay.biz/'
repo_name: 'mcplay/wiki'
repo_url: 'https://github.com/mcplay/wiki'

theme:
  name: 'material'
  language: 'ja'
  custom_dir: 'custom'
  palette:
    primary: 'Blue Grey'
    accent: 'Blue Grey'
  feature:
    - tabs
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - ja

extra:
  social:
    - type: fontawesome/brands/github-alt
      link: https://github.com/mcplay
    - type: fontawesome/brands/twitter
      link: https://twitter.com/MCPlayNetwork

markdown_extensions:
    - admonition

nav:
  - ホーム: index.md
  - サバイバル:
    - サバイバルについて: Survival/index.md
    - ワールド: Survival/worlds.md
    - MyPet: Survival/MyPet.md
    - GriefPrevention: Survival/GriefPrevention.md
    - mcMMO: Survival/mcMMO.md
